

export const FETCH_USER = 'FETCH_USER';
export const LOGIN_ATTEMPT = 'LOGIN_ATTEMPT';
export const DESELECT_GARAGE_GUIDE_QUOTE = 'DESELECT_GARAGE_GUIDE_QUOTE';
export const SELECT_GARAGE_GUIDE_QUOTE = 'SELECT_GARAGE_GUIDE_QUOTE';
export const CALLBACK_REQUEST = 'CALLBACK_REQUEST';
export const CALLBACK_REQUESTS = 'CALLBACK_REQUESTS';
export const FETCH_GARAGE_GUIDE_QUOTES = 'FETCH_GARAGE_GUIDE_QUOTES';
export const FETCH_GARAGE_OFFICIAL_QUOTES = 'FETCH_GARAGE_OFFICIAL_QUOTES';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT_SUCCESS= 'LOGOUT_SUCCESS';

export const CREATE_USER_REQUEST= 'CREATE_USER_REQUEST';
export const CREATE_USER_SUCCESS= 'CREATE_USER_SUCCESS';
export const CREATE_USER_FAILURE= 'CREATE_USER_FAILURE';

export const UPDATE_USER_REQUEST= 'UPDATE_USER_REQUEST';
export const UPDATE_USER_SUCCESS= 'UPDATE_USER_SUCCESS';
export const UPDATE_USER_FAILURE= 'UPDATE_USER_FAILURE';
